### ISSUE TITLE
Workshop Todo

### ISSUE THREAD

**Issue by deece** [InfernoEmbedded/HomeAutomationWorkshop#1]
- [x] Lasercut solder stencil for Home Automation boards
- [x] Assemble & test 1 x home automation boards per attendee (Omit 24V diode - it's getting too warm)
- [x] Identify & publish prerequisites
- [x] Fit Home Automation boards to Orange Pi Primes
- [x] Boot test machines, ensure the I2C 1wire interface is detected, the DS18B20 sensor is detected and a remote 1wire device is detected on the Onewire port. Record the MAC address and number the board
- [x] Create a Home Assistant plugin containing OWFS (with our fixes) and our MQTT bridge
- [x] Assemble and test 2 x 16 channel 1wire SSR control boards per attendee
- [x] Expose GPIO in Home Assistant
- [x] Create Workshop instructions
- [x] Dry run Workshop instructions
- [ ] Design cases for the hardware
- [ ] Print cases for the hardware
- [x] Tally costs & provide payment details
- [x] Configure an OpenWRT machine as a router & DHCP server so we can identify the IP address or each machine on the day
